# Plugin List

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # Asynchronous
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]] # Status bar
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # Change filetype
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # File Tree
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost * Neomake
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'tpope/vim-fugitive'

# nvim
[[plugins]]
repo = 'Shougo/deoplete.nvim'
