# Plugin List

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # Asynchronous
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = ['context_filetype.vim']

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
[[plugins]] # Status bar
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # Change filetype
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # File Tree
repo = 'scrooloose/nerdtree'

[[plugings]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]] # Color
repo =  'w0ng/vim-hybrid'

[[plugins]]
repo = 'neomake/neomake'

[[plugings]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'greyblake/vim-preview'

